import turtle
text="Tower of Tophane \n (Tomb of Ottoman Sultan Osman)"
turtle.bgcolor("black")
t=turtle.Turtle()
t.pensize(2)
t.speed(100)
def q():
    t.left(90)
    t.fd(50)
    t.backward(50)
    t.right(90)
t.color("grey")
t.begin_fill()
t.fd(50)
t.left(90)
for i in range(5):
    t.fd(50)
    q()
t.right(-90)
t.fd(50)
t.left(90)
for i in range(5):
    t.fd(50)
    q()
t.left(90)
def windows():
    t.fd(17.5)
    t.left(90)
    t.fd(15)
    t.right(180)
    t.circle(7.5,-180)
    t.right(180)
    t.fd(15)
    t.left(90)
    t.fd(17.5)
    t.backward(50)
for i in range(5):
    windows()
    t.left(90)
    t.fd(50)
    t.right(90)
t.fd(5)
t.begin_fill()
t.color("sandybrown")
for i in range(4):
    t.fd(40),t.left(90)
t.end_fill()
t.fd(24)
t.left(90)
t.fd(24)
t.color("brown")
t.begin_fill()
t.circle(7)
t.end_fill()
t.color("red")
t.up()
t.fd(16)
t.down()
t.fd(50)
for i in range(2):
    t.begin_fill()
    t.fd(50)
    t.right(90)
    t.fd(75)
    t.right(90)
    t.end_fill()
t.right(90)
t.up(),t.goto(-470,300)
t.down()
t.write(text, align="left", font=("Arial", 20, "bold"))
t.up()
t.goto(900,900)
turtle.done()
###tophane###

